name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get Version
        id: extract_version
        run: | 
          LATEST_VERSION=$(cat ./oneware-package.json | jq -r '.versions | max_by(.version | split(".") | map(tonumber)) | .version')
          echo "Latest version is $LATEST_VERSION"
          echo "{latest_version}={$LATEST_VERSION}" >> $GITHUB_OUTPUT
      - name: Compress
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ./OneWare.Max1000_${{ steps.extract_version.outputs.latest_version }}_all.zip
          directory: ./
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./OneWare.Max1000_${{ steps.extract_version.outputs.latest_version }}_all.zip"
          tag: ${{ steps.extract_version.outputs.latest_version }}
          allowUpdates: true
